aspnet/Microsoft.Data.Sqlite

build.cmd, tools/DataCommon.SQLite.targets
- Change default packages path
- Change KRE to DOTNET
@davidfowl
=> React to runtime renaming

build.cmd, build.sh, src/Microsoft.Data.SQLite/Interop/NativeMethods.cs, src/Microsoft.Data.SQLite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.SQLite/project.json, test/Microsoft.Data.SQLite.Tests/project.json
Prepping to be merged once ready.
=> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteParameterCollection.cs, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/project.json
This may (or may not) enable Mono/Xamarin. I'll let @rowanmiller test it. :wink:
=> Target net45 and net45+win

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteParameterCollection.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
=> Throws errors when executing query with unset parameters

README.md
=> ASP.NET vNext -> ASP.NET 5

src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs
=> Expose native methods

.gitignore, Microsoft.Data.Sqlite.sln.DotSettings, src/Microsoft.Data.Sqlite/CacheMode.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteParameterCollection.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Add Resharper code formatting settings and run code cleanup.
=> Run code cleanup

src/Microsoft.Data.Sqlite/project.json
/cc @bricelam 
Base on release branch.
=> netportabl50 -> dotnet

src/Microsoft.Data.Sqlite/project.json
=> dotnet all the things

.gitignore, .travis.yml, README.md, makefile.shade, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
SQLite download fails on Mono because of https://bugzilla.xamarin.com/show_bug.cgi?id=30686
=> Workaround for the SQLite download step in our build

README.md
Only reason I can think not to put this on here: it only tests Mono.
Thoughts?
=> Add Travis-CI status images to README.md

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs, test/Microsoft.Data.Sqlite.Tests/project.json
=> Remove dependency on System.Threading.Thread

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/project.json
=> Skip NativeLibraryLoader on non-Windows platforms

.travis.yml, install_dependencies.sh
=> Specify mono versions

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
Fixes https://github.com/aspnet/EntityFramework/issues/2936
=> Fix bug in parameter binding with UTF8 strings

makefile.shade, src/Microsoft.Data.Sqlite/project.json
Note, this depends on DNX 1.0.0-beta8-15552 or newer.
~~@anurse These don't seem to be making it into the nupkg...~~
=> Use new packInclude property in project.json

src/Microsoft.Data.Sqlite/CacheMode.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteException.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteParameterCollection.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, src/Microsoft.Data.Sqlite/SqliteType.cs
=> Add XML documentation to public properties, methods, and classes.

build.sh, makefile.shade
=> Run tests against coreclr on darwin/linux

src/Microsoft.Data.Sqlite/SqliteFactory.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteFactoryTest.cs
=> Add DbProviderFactory implementation

src/Microsoft.Data.Sqlite/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
=> Ignore CommandBehavior.SequentialAccess

makefile.shade
Resolves #138
Additional verification: I ran the tests on `dnx-clr-win-x64` and `dnx-coreclr-win-x64`
=> Update to SQLite 3.9.0 (with new win-x64 library)

src/Microsoft.Data.Sqlite/project.json
=> Workaround for DNX packInclude

src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
=> Support CommandBehavior.CloseConnection

.gitignore, makefile.shade, src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteFactory.cs, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/build/net451/Microsoft.Data.Sqlite.props, src/Microsoft.Data.Sqlite/build/uap10.0/Microsoft.Data.Sqlite.targets, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs
Also includes cleanup from the dnx451 to net451 change and other minor refactorings.
Resolves #128, fixes #134
=> Fix native library loading

src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
=> Automatically prefix SqliteParameter names during binding

src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.FunctionalTests.UWP/Microsoft.Data.Sqlite.FunctionalTests.UWP.csproj, test/Microsoft.Data.Sqlite.FunctionalTests.UWP/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Always adjust relative paths to the ApplicationBasePath.
Fix #55
=> Automatically adjust relative paths

src/Microsoft.Data.Sqlite/SqliteConnection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
=> Enable enabling loading extensions

src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs, src/Microsoft.Data.Sqlite/Interop/Sqlite3Handle.cs, src/Microsoft.Data.Sqlite/Interop/Sqlite3StmtHandle.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteCacheMode.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteOpenMode.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, src/Microsoft.Data.Sqlite/SqliteType.cs, src/Microsoft.Data.Sqlite/Strings.resx, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/TestUtilities/Constants.cs
This also...
* Removes the PlatformAbstractions dependency (resolves #180)
* Fixes #188
Resolves #182
=> Add Mode connection string option

.gitignore, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs
see https://github.com/aspnet/PlatformAbstractions/issues/2
cc @bricelam
=> Workaround TD.net bug

src/Microsoft.Data.Sqlite/SqliteConnection.cs
=> Replace call to Windows.Storage via DLR with reflection calls.

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Return empty byte array

src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, src/Microsoft.Data.Sqlite/Utilities/DbConnectionExtensions.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
=> Fix bug in opening serializable transactions

.gitignore, global.json, makefile.shade, src/Microsoft.Data.Sqlite/Properties/Microsoft.Data.Sqlite.rd.xml, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/Strings.resx, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/project.json
=> Test using .NET Core CLI

NuGetPackageVerifier.json, src/Microsoft.Data.Sqlite/project.json
=> Enabled xml doc generation

src/Microsoft.Data.Sqlite/Properties/AssemblyInfo.cs
=> Added AssemblyProduct attribute

src/Microsoft.Data.Sqlite/SqliteConnection.cs
=> Add overrides for default base directory

.gitignore, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/Utilities/ApplicationDataHelper.cs
=> Make the first and only call to set temp_store_directory thread safe

.gitattributes, src/Microsoft.Data.Sqlite/project.json
Part of https://github.com/aspnet/EntityFramework/pull/5021
=> Cross-compile to netcore50 to support EF on UWP

test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs, test/Microsoft.Data.Sqlite.Tests/project.json
=> Migrate tests/samples/tools to portable

makefile.shade, test/Microsoft.Data.Sqlite.Tests/TestUtilities/WinSqlite3TestFixture.cs
=> Run tests a second time if winsqlite3 is available

src/Microsoft.Data.Sqlite/Utilities/ApplicationDataHelper.cs
=> [tiny] React to change in type loader in .NET Core

src/Microsoft.Data.Sqlite/project.json
cc @natemcmaster @rowanmiller @Eilon
=> Update package description and tags

src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteCacheMode.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteEngine.cs, src/Microsoft.Data.Sqlite/SqliteException.cs, src/Microsoft.Data.Sqlite/SqliteFactory.cs, src/Microsoft.Data.Sqlite/SqliteOpenMode.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/SqliteParameterCollection.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, src/Microsoft.Data.Sqlite/SqliteType.cs, src/Microsoft.Data.Sqlite/Strings.resx, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
=> Add XML doc comments

src/Microsoft.Data.Sqlite/Internal/SqliteEngine.cs, test/Microsoft.Data.Sqlite.Tests/Internal/SqliteEngineTest.cs, test/Microsoft.Data.Sqlite.Tests/TestUtilities/WinSqlite3TestFixture.cs
=> Move SqliteEngine to Microsoft.Data.Sqlite.Internal

src/Microsoft.Data.Sqlite/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Implement SqliteDataReader.GetEnumerator() on .NET Standard

test/Microsoft.Data.Sqlite.Tests/project.json
cc @natemcmaster \ @ajaybhargavb
=> Updating to RTM builds of xunit

src/Microsoft.Data.Sqlite/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Fix https://github.com/aspnet/EntityFramework/issues/6205
cc @divega
=> Parse decimal numbers in exponential form

src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.tt, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/NativeLibraryLoaderTest.net451.cs
=> Include assembly location and app domain bin path in search for sqlite3.dll

README.md
=> Cleanup package lisiting on README.md

src/Microsoft.Data.Sqlite/project.json
=> SQLite 3.13.0

test/Microsoft.Data.Sqlite.Tests/project.json
Not sure if this package is still needed, but if it is, we need to update its version number.
cc @pranavkm
=> Update partner packages

src/Microsoft.Data.Sqlite/project.json
Reverses https://github.com/aspnet/Microsoft.Data.Sqlite/pull/301
Fixes https://github.com/aspnet/EntityFramework/issues/7040
cc @bricelam
=> Revert to SQLite 3.12.3

src/Microsoft.Data.Sqlite/project.json
=> Port: Revert to SQLite 3.12.3

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
=> Sleep in ExecuteReader timeout loop on net451

NuGet.config
=> Unblock CI

build/dependencies.props, src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj, src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj, test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
Lift all version numbers into the dependencies.props folder.
=> Unify dependency versions to one file

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Support reading Guid values from TEXT columns

src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj, src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
Implements SqliteCommand.Prepare according to the remarks in the issue.
Addresses #235
=> Implement SqliteCommand.Prepare.

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
=> Always get results from statements that return them

build/dependencies.props
@Eilon can we get approval?
This fixes our issues with NuGet packaging (ericsink/SQLitePCL.raw#140) and winsqlite3.dll (ericsink/SQLitePCL.raw#149)
cc @JunTaoLuo
=> Update to SQLitePCL.raw 1.1.3

build/dependencies.props
Related: https://github.com/aspnet/BuildTools/pull/244
=> Update SqlitePCLRaw version

build/dependencies.props
Workaround for https://github.com/ericsink/SQLitePCL.raw/issues/162.
cc @bricelam @mikeharder
=> Revert to SQLitePCLRaw 1.1.3

src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs, src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
(may want to view [without whitespace changes](https://github.com/aspnet/Microsoft.Data.Sqlite/pull/386/files?w=1))
=> Dispose all the things

build/dependencies.props, src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Removes workaround for ericsink/SQLitePCL.raw#166
cc @Eilon for OSS approval
=> Update to SQLitePCL.raw 1.1.8

build/common.props, build/dependencies.props, src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj, test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Fixes the issue in Test Explorer source mapping.
=> Upgrade to xunit 2.3.0-beta4

src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Allow reading char from TEXT

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
=> Add a note about file creation to SqliteConnection.Open()

src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs, src/Microsoft.Data.Sqlite.Core/SqliteParameterBinder.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
=> Implement SqliteParameter: Truncate data to Size

src/Microsoft.Data.Sqlite.Core/SqliteException.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
=> Use extended Sqlite error codes

src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs, src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, src/Microsoft.Data.Sqlite.Core/SqliteParameterReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs, tools/Resources.tt
=> Don't throw InvalidCastException, throw customized InvalidOperationException instead

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, src/Microsoft.Data.Sqlite.Core/SqliteException.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
=> Add online backup.

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
=> Override DbConnection.DbProviderFactory

src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs, version.props
=> [2.0.1] Revert to using IMMEDIATE with Serializable transactions

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
=> Add SqliteConnection.DefaultTimeout

build/dependencies.props
Resolves https://github.com/aspnet/EntityFrameworkCore/issues/10724
Includes support for Alpine Linux and "portable" windows RIDs (win-x64/win-x86)
cc @ericsink
=> Update to SQLitePCLRaw 1.1.10-pre20180223200113

build/dependencies.props
FYI @ericsink
Although Universe will automatically flow this through once https://github.com/aspnet/Universe/pull/1010 is merged, I opened this PR here so we can get PR validation on multiple platforms that all tests still pass.
=> Update to SQLitePCLRaw 1.1.10

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
This conforms better with the semantics of CommandTimeout. Multiple statements now count toward the same timeout. Removed sqlite3_busy_timeout since was using the full timeout for every SQLITE_BUSY encountered.
Busy errors encountered while preparing statements are also now retried.
Fixes #408
=> Update busy retry logic

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
=> [2.1] Preserve original SQL when retrying sqlite3_prepare_v2()

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Add GetBytes, GetChars and GetStream to SqliteDataReader

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
=> Handle externally rolled back transactions

samples/BulkInsertSample/Program.cs
- add `transaction.Commit()` to apply changes made in the transaction. otherwise, none of the data gets inserted.
=> fix Bulk Insert sample

Directory.Build.targets, build/dependencies.props, build/repo.props
@bricelam for best guess on who might "own" this repo. If it's not you please let me know who would be better suited.
We're removing these extra framework referenced as part of [investigating this](https://github.com/aspnet/Coherence-Signed/issues/1062#issuecomment-423590031) to see if it resolves the issue.
=> Remove un-needed framework references

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
=> Clear cached data records while stepping.
