src/Microsoft.Data.Sqlite/CacheMode.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Add option to enable shared-cache on new connections.
https://www.sqlite.org/sharedcache.html
Also improves the calls added to #82
=> Add shared-cache connection option

.gitignore, src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/SqliteParameter.cs
This allows shared_cache on OS X and iPhone. Also it has the advantage of setting Cache=Shared only for the currently opened connection and does not tamper with global settings.
Fixes #88.
=> Use sqlite3_open_v2 instead && use UTF-8

.gitignore, src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/SqliteDataReader.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs, test/Microsoft.Data.Sqlite.Tests/project.json
When a SQLite statement causes an error sqlite3_step, the statement object was not disposed.
Add test cases to replicate https://github.com/aspnet/EntityFramework/issues/2356.
Improved error messages for SQL errors
=> Fix memory leak.

.gitignore, src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, src/Microsoft.Data.Sqlite/project.json, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs
Implements a timeout option on the connection string. Default timeout = 30s
Users can modify this with the connection string `Data Source =test.db; Timeout=10 `
This handles SQLITE_LOCKED and SQLITE_BUSY, and throws a `TimeoutException` if they are not handled within the timeout specified in the connection string.
Works for both cache modes (Shared and Private).
TODO: perf
Fixes #97
=> Implement command timeouts 

src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs, src/Microsoft.Data.Sqlite/project.json
Workaround aspnet/dnx#2594.
Fixes #121 
The code is right and should work, but cannot verify on OS X until DNX fixes other major issues with osx/coreclr.
=> Detect OS using DNX

src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteConnectionCacheMode.cs, src/Microsoft.Data.Sqlite/SqliteConnectionStringBuilder.cs, src/Microsoft.Data.Sqlite/SqliteTransaction.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
Add "Filename" alias to connection string builder
Rename CacheMode to SqliteConnectionCacheMode.
=> Minor API tweaks. Add "Filename" synonym to connection string builder.

test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.xproj, test/Microsoft.Data.Sqlite.Tests/TestUtilities/SqliteTestFramework.cs, test/Microsoft.Data.Sqlite.Tests/xunit.runner.json
Add debugging info to display the version of SQLite used.
Currently, if sqlite3.dll cannot import, then we get 239 errors, all with the same message. This short-circuits and cancels all testing if sqlite3.dll does not import.
=> [testing] Fail all tests if sqlite3.dll cannot be imported

.travis.yml, README.md, src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Interop/Sqlite3Handle.cs, src/Microsoft.Data.Sqlite/Interop/VersionedMethods.cs, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs, test/Microsoft.Data.Sqlite.Tests/TestUtilities/SqliteVersionConditionAttribute.cs
SQLite 3.7.9 is the default library version on Travis Linux agents.
3.7.13 is the default version on aspnet-docker (Fix https://github.com/aspnet/aspnet-docker/issues/85) and Travis OSX agents.
Fallback to older sqlite3 calls when using older versions of sqlite3.
sqlite3_close and sqlite3_errstr do not exist < 3.7.15
sqlite3_db_filename does not exist < 3.7.10
Add internal utilities for working with different sqlite versions and testing.
Add OSX and Mono alpha to test matrix.
=> Support SQLite 3.7.9

src/Microsoft.Data.Sqlite/SqliteParameter.cs, src/Microsoft.Data.Sqlite/project.json
For some strange reason, the mono c# compiler catches more issues than csc. Here are the compiler errors/warnings being fixed in this commit:
```
/Users/dfowler/dev/git/ProjectK/Universe/Microsoft.Data.Sqlite/src/Microsoft.Data.Sqlite/SqliteDataReader.cs(135,25): error CS0012: The type `System.Xml.Serialization.IXmlSerializable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```
```
/Users/dfowler/dev/git/ProjectK/Universe/Microsoft.Data.Sqlite/src/Microsoft.Data.Sqlite/SqliteParameter.cs(272,17): error CS0219: Warning as Error: The variable `count' is assigned but its value is never used
```
=> Fixed mono compiler issues

src/Microsoft.Data.Sqlite/Interop/MarshalEx.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.tt, src/Microsoft.Data.Sqlite/Interop/Sqlite3Handle.cs, src/Microsoft.Data.Sqlite/Interop/VersionedMethods.cs, src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.xproj, src/Microsoft.Data.Sqlite/Properties/Strings.Designer.cs, src/Microsoft.Data.Sqlite/SqliteConnection.cs, src/Microsoft.Data.Sqlite/SqliteEngine.cs, src/Microsoft.Data.Sqlite/Strings.resx, test/Microsoft.Data.Sqlite.Tests/SqliteEngineTest.cs
To use, call `SqliteEngine.UseWinSqlite3()` before using SQLite.
Fixes #179
=> Enable using winsqlite3.dll

src/Microsoft.Data.Sqlite/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
This adds `CommandBehavior.SingleResult` and `CommandBehavior.SingleRow` to the ignored "list", addressing #220
=> Add CommandBehavior.SingleResult and CommandBehavior.SingleRow to ignored behaviors

src/Microsoft.Data.Sqlite/Interop/Constants.cs, src/Microsoft.Data.Sqlite/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConcurrencyTest.cs, test/Microsoft.Data.Sqlite.Tests/TestUtilities/Constants.cs
Can occur in multi-threaded context. This fixes failing concurrency tests that started failing on OSX and Linux.
Possibly the cause of #222
cc @bricelam
=> Fix for SQLITE_BUSY errors throw before command timeout expired

.gitignore, .travis.yml
dotnet requires OSX >= 10.10
Travis agents are OSX 10.9.5
=> Disable OSX on Travis

src/Microsoft.Data.Sqlite/project.json
Because of the impending doom of PJ. 3.12.3 includes a fix for https://github.com/natemcmaster/libsqlite3-package/issues/8, which is that 3.12.2 uses the existence of a file named "project.json" to determine if it is in nuget3 or not...which is not longer the right way to detect this.
cc @bricelam
=> :arrow_up: SQLite to 3.12.3

src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.cs, src/Microsoft.Data.Sqlite/Interop/NativeMethodsImpl.tt
Fixes #342 
Verification: Manually verified that debugging works now.
=> [1.1.1] Use CallingConvention.StdCall with winsqlite3.dll

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
They would eventually get freed with the connection, but this will free them sooner when an undisposed reader is finalized and the connection is still open.
Fixes #351
This also re-enables API check (fixes #338)
=> Fix sqlite3_stmt leak

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
=> Add SqliteConnection.CreateCollation method

build/common.props, build/dependencies.props, src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj, src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteException.cs, src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj, test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Ideally, we'd just target .NET Standard 2.0, but since it will take a few months for UWP to support it, we'll cross-target 1.4 in the mean time. (See https://github.com/aspnet/Microsoft.Data.Sqlite/pull/370/commits/64319deb873fea6df8d9903ce3fd4997a07a89f9 for the code we'll be able to remvoe.)
Blocked waiting on updates to KoreBuild
Resolves #350
=> Target .NET Standard 1.4 & 2.0

build/dependencies.props, src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
These packages won't be shipping in the 2.0 wave, but are still required when targeting 1.x.
=> Downgrade to valid package versions

build/dependencies.props
This bundles SQLite 3.18.2 and has improved support for .NET Standard 2.0 and NuGet 4.3.
cc @ericsink
=> Upgrade SQLitePCLRaw to 1.1.7

src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
This prevents integer results when performing arithmetic operations on decimal parameters. For example, consider the following query.
```SQL
SELECT 1 / $value;
```
Where `value` is the following in C#.
```C#
decimal value = 2m;
```
Here is a table illustrating the improved result.
Microsoft.Data.Sqlite | Result
--- | ---
**1.x** |  0
**2.0.0** | 0.5
You may encounter a breaking change if you previously saved integral decimal values into a column using version 1.x and try to query for equality in version 2.0.0.
For example, if you previously saved the value `3m` into `DecimalColumn` and try the following query in version 2.0 (where `$value` is also `3m`) it will return no results.
```SQL
SELECT *
FROM MyTable
WHERE DecimalColumn = $value;
--              '3' = '3.0'   (False)
```
To …
=> Ensure decimal point in decimal parameters

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
According to http://sqlite.org/c3ref/stmt.html the life cycle of a prepared statement looks like this:
1. Create the prepared statement object using sqlite3_prepare_v2(). 
2. Bind values to parameters using the sqlite3_bind_*() interfaces. 
3. Run the SQL by calling sqlite3_step() one or more times. 
4. Reset the prepared statement using sqlite3_reset() then go back to step 2. Do this zero or more times. 
5. Destroy the object using sqlite3_finalize(). 
Since we now store and reuse prepared statements we have to reset them before rebinding (4->2).
This reset got lost somewhere in the process of adding the Prepare() command.
Addresses #394
=> Fix broken reuse of SqliteCommand

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Adds GetTimeSpan to SqliteDataReader and implements conversion from REAL to TimeSpan (assumed is that the value represents the fractional number of days (e.g. as result of a subtraction of two Julian date values)).
Addresses #411
=> Allow reading TimeSpan from INTEGER/REAL

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Add initial implementation of DbDataReader.GetSchemaTable.
This is based on the table in #253. The null entries are commented out at the moment. For the sequence of columns I used the same order as in SqlDataReader (https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlDataReader.cs,451).
sqlite3_table_column_metadata is not supported by SQLitePCL.raw yet, so that IsKey, AllowDBNull and IsAutoIncrement are not implemented.
Addresses #253
=> Add initial implementation of GetSchemaTable

src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj, src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
Changes:
- Set min client version to 3.6
- Block metapackage on incompatible frameworks
=> NuGet: Friendlier .NET Standard 2.0 packages

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs, src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Note that column and table names cannot be bound using parameters (I enclosed them in " to make SQL injection attacks less likely).
Addresses #436
=> Improve SqliteDataReader.GetSchemaTable() DataType

src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs, src/Microsoft.Data.Sqlite.Core/SqliteParameterBinder.cs, src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
In order to leave the default behaviour (for char and Guid) unchanged I added SqliteType.Undefined and used it as new default value for SqliteType (was Text before).
Addresses #418
=> Implements SqliteParamter: Honor SqliteType

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs, test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
I ran the tests once with `raw.sqlite3_extended_result_codes(_db, 1);` added to `Connection.Open` and only the test `ExecuteReader_retries_when_locked` failed.
Addresses #459
=> Handle extended result codes

src/Microsoft.Data.Sqlite.Core/SqliteParameterCollection.cs, test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
Using the `AddRange(Array values)` method causes a exception because the result of linq `Cast<SqliteParameter>()` returns a `IEnumerable<T>` which cannot be casted to a single `SqliteParameter`.
The exception thrown: Unable to cast object of type `'<CastIterator>d__34`1[Microsoft.Data.Sqlite.SqliteParameter]' to type 'Microsoft.Data.Sqlite.SqliteParameter'.`
The method `AddRange `comes into place when working primarily with the base class `DbParameterCollection `which does not have a method accepting `IEnumerable<SqliteParameter>`
=> Fix AddRange(Array values)

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Without this, they're finalized in later generations
Fixes #506
=> Eagerly free sqlite3_stmt objects during SqliteCommand finalization

src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
- With the methods that return the number of bytes that are read, it should be expected that they should safeguard against reading over the buffer length especially since the user might not know the length beforehand. 
- Before this patch, if you stuck in a length that was larger than the rest of the buffer size, the `Array.Copy` would throw an argument exception. Now, after this patch it behaves like `Stream.Read`.
There didn't seem to be an bug# associated with this. I found it when integrating the latest nightly into my app.
=> Simple overflow checking on GetBytes and GetChars

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Prepared statements are a thing since 6eaf137519e3f421551b53399abe386e65d0f8ce
=> Remove an overmodest comment in the API docs

src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs, test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
OK, this looks better.
Have GetBytes() handle buffer null value appropriately without the need for code external to this API to do so.
I'd like to get this fix into 2.2.0 release.  Thank you.
=> Check for null in buffer[] and return appropriate value
